---
- name: "Push docker images to any docker registry"
  collections: 
    - oracle.oci
  hosts: local
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  become: yes
  tasks:
    - name: Create container repository
      shell:
              # required - Added below command to create OCI repo in the compartment
        oci --auth instance_principal artifacts container repository create --compartment-id "{{ compartment_id }}" --display-name "sunbird5/{{ image_name }}"
    - name: login to registry
      docker_login:
        registry: "{{ vault_docker_registry_url }}"
        username: "{{ vault_docker_registry_user }}"
        password: "{{ vault_docker_registry_password }}"
      tags: docker-login

    - name: Push image to registry
      docker_image:
        name: "{{ hub_org }}/{{ image_name }}:{{ image_tag }}"
        push: yes
   
    - file:
        path: "/root/.docker"
        state: absent
